namespace pvs.input {

	public enum InputCommandType {
		SELECT_BUILDING_TEMPLATE,
		DISABLE_BUILDING_MODE,
		SHOW_ALL_BUILDINGS_PANEL,
		
		RESET_BUILDINGS,
		SAVE_BUILDINGS,
		
		LEFT_MOUSE_BUTTON_UP,
		RIGHT_MOUSE_BUTTON_UP,
		KEY_UP,
	}
}